<?php $clickheatConf = array (
  'logPath' => '/var/www/diw.2daw/web/clickheat/assets/clickheat-master/logs/',
  'cachePath' => '/var/www/diw.2daw/web/clickheat/assets/clickheat-master/cache/',
  'referers' => false,
  'groups' => false,
  'filesize' => 0,
  'adminLogin' => 'quevedo',
  'adminPass' => '98c6ff171df97a865e50e396f4427d33',
  'viewerLogin' => 'carlosbouzas',
  'viewerPass' => '98c6ff171df97a865e50e396f4427d33',
  'memory' => 2,
  'step' => 5,
  'dot' => 19,
  'flush' => 40,
  'start' => 'm',
  'palette' => true,
  'heatmap' => true,
  'hideIframes' => true,
  'hideFlashes' => true,
  'yesterday' => true,
  'alpha' => 80,
  '__screenSizes' => 
  array (
    0 => 0,
    1 => 240,
    2 => 640,
    3 => 800,
    4 => 1024,
    5 => 1152,
    6 => 1280,
    7 => 1440,
    8 => 1600,
    9 => 1800,
  ),
  '__browsersList' => 
  array (
    'all' => '',
    'msie' => 'Internet Explorer',
    'firefox' => 'Firefox',
    'chrome' => 'Chrome',
    'safari' => 'Safari',
    'opera' => 'Opera',
    'unknown' => '',
  ),
  'version' => '1.16',
); ?>